export const InitialValues = {
  username: "",
  email: "",
  phone: "",
  work: "",
  country: "",
  id_government: "",
  birth_date: "",
  streetAddress: "",
  city: "",
  stateProvince: "",
  zipPostalCode: "",
  account_name: "",
  account_number: "",
  current_balance: "",
};
